In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/twitter_sentiment_dataset.csv',encoding='iso-8859-1')

In [ ]:
df.head(20)

sentiment  ...                                               text
0           0  ...  is upset that he can't update his Facebook by ...
1           0  ...  @Kenichan I dived many times for the ball. Man...
2           0  ...    my whole body feels itchy and like its on fire 
3           0  ...  @nationwideclass no, it's not behaving at all....
4           0  ...                      @Kwesidei not the whole crew 
5           0  ...                                        Need a hug 
6           0  ...  @LOLTrish hey  long time no see! Yes.. Rains a...
7           0  ...               @Tatiana_K nope they didn't have it 
8           0  ...                          @twittera que me muera ? 
9           0  ...        spring break in plain city... it's snowing 
10          0  ...                         I just re-pierced my ears 
11          0  ...  @caregiving I couldn't bear to watch it.  And ...
12          0  ...  @octolinz16 It it counts, idk why I did either...
13          0  ...  @smarrison i would've been the first, but i di...
14          0  ...  @iamjazzyfizzle I wish I got to watch it with ...
15          0  ...  Hollis' death scene will hurt me severely to w...
16          0  ...                               about to file taxes 
17          0  ...  @LettyA ahh ive always wanted to see rent  lov...
18          0  ...  @FakerPattyPattz Oh dear. Were you drinking ou...
19          0  ...  @alydesigns i was out most of the day so didn'...

[20 rows x 6 columns]

In [ ]:
df.tail()

sentiment  ...                                               text
1048570          4  ...           My GrandMa is making Dinenr with my Mum 
1048571          4  ...  Mid-morning snack time... A bowl of cheese noo...
1048572          4  ...  @ShaDeLa same here  say it like from the Termi...
1048573          4  ...             @DestinyHope92 im great thaanks  wbuu?
1048574          4  ...               cant wait til her date this weekend 

[5 rows x 6 columns]

In [ ]:
df.shape

(1048575, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype 
---  ------      --------------    ----- 
 0   sentiment   1048575 non-null  int64 
 1   Unnamed: 1  1048575 non-null  int64 
 2   Unnamed: 2  1048575 non-null  object
 3   Unnamed: 3  1048575 non-null  object
 4   Unnamed: 4  1048575 non-null  object
 5   text        1048575 non-null  object
dtypes: int64(2), object(4)
memory usage: 48.0+ MB


In [ ]:
df=df.drop(columns=['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 2 columns):
 #   Column     Non-Null Count    Dtype 
---  ------     --------------    ----- 
 0   sentiment  1048575 non-null  int64 
 1   text       1048575 non-null  object
dtypes: int64(1), object(1)
memory usage: 16.0+ MB


In [ ]:
df['sentiment'] = df['sentiment'].map({0:0, 4:1})

In [ ]:
df

sentiment                                               text
0                0  is upset that he can't update his Facebook by ...
1                0  @Kenichan I dived many times for the ball. Man...
2                0    my whole body feels itchy and like its on fire 
3                0  @nationwideclass no, it's not behaving at all....
4                0                      @Kwesidei not the whole crew 
...            ...                                                ...
1048570          1           My GrandMa is making Dinenr with my Mum 
1048571          1  Mid-morning snack time... A bowl of cheese noo...
1048572          1  @ShaDeLa same here  say it like from the Termi...
1048573          1             @DestinyHope92 im great thaanks  wbuu?
1048574          1               cant wait til her date this weekend 

[1048575 rows x 2 columns]

In [ ]:
df['text']=df['text'].str.lower()


In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
swords=stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
swords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
def remove_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in swords])

df['text'] = df['text'].apply(lambda text: remove_stopwords(text))
df['text'].head(20)

0     upset can't update facebook texting it... migh...
1     @kenichan dived many times ball. managed save ...
2                      whole body feels itchy like fire
3     @nationwideclass no, behaving all. i'm mad. he...
4                                  @kwesidei whole crew
5                                              need hug
6     @loltrish hey long time see! yes.. rains bit ,...
7                                       @tatiana_k nope
8                                 @twittera que muera ?
9                    spring break plain city... snowing
10                                      re-pierced ears
11    @caregiving bear watch it. thought ua loss emb...
12    @octolinz16 counts, idk either. never talk any...
13    @smarrison would've first, gun. really though,...
14    @iamjazzyfizzle wish got watch you!! miss @iam...
15    hollis' death scene hurt severely watch film w...
16                                           file taxes
17    @lettya ahh ive always wanted see rent lov

In [ ]:
import string

def remove_punctuations(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

df['text']= df['text'].apply(lambda x: remove_punctuations(x))
df['text'].head(20)

0     upset cant update facebook texting it might cr...
1     kenichan dived many times ball managed save 50...
2                      whole body feels itchy like fire
3     nationwideclass no behaving all im mad here ca...
4                                   kwesidei whole crew
5                                              need hug
6     loltrish hey long time see yes rains bit only ...
7                                         tatianak nope
8                                   twittera que muera 
9                       spring break plain city snowing
10                                       repierced ears
11    caregiving bear watch it thought ua loss embar...
12      octolinz16 counts idk either never talk anymore
13    smarrison wouldve first gun really though zac ...
14    iamjazzyfizzle wish got watch you miss iamliln...
15    hollis death scene hurt severely watch film wr...
16                                           file taxes
17    lettya ahh ive always wanted see rent love

In [ ]:
import re
def remove_URLs(data):
    return re.sub('((www.[^s]+)|(https?://[^s]+))',' ',data)

df['text'] = df['text'].apply(lambda x: remove_URLs(x))
df['text'].tail()


1048570                            grandma making dinenr mum
1048571        midmorning snack time bowl cheese noodles yum
1048572    shadela say like terminiator movies comes like...
1048573                  destinyhope92 im great thaanks wbuu
1048574                           cant wait til date weekend
Name: text, dtype: object

In [ ]:
def remove_numbers(data):
    return re.sub('[0-9]+', '', data)

df['text'] = df['text'].apply(lambda x: remove_numbers(x))
df['text'].head(20)

0     upset cant update facebook texting it might cr...
1     kenichan dived many times ball managed save  r...
2                      whole body feels itchy like fire
3     nationwideclass no behaving all im mad here ca...
4                                   kwesidei whole crew
5                                              need hug
6     loltrish hey long time see yes rains bit only ...
7                                         tatianak nope
8                                   twittera que muera 
9                       spring break plain city snowing
10                                       repierced ears
11    caregiving bear watch it thought ua loss embar...
12        octolinz counts idk either never talk anymore
13    smarrison wouldve first gun really though zac ...
14    iamjazzyfizzle wish got watch you miss iamliln...
15    hollis death scene hurt severely watch film wr...
16                                           file taxes
17    lettya ahh ive always wanted see rent love

In [ ]:
sentences = df['text'].tolist()
labels = df['sentiment'].tolist()

In [ ]:
sentences

['upset cant update facebook texting it might cry result school today also blah',
 'kenichan dived many times ball managed save  rest go bounds',
 'whole body feels itchy like fire',
 'nationwideclass no behaving all im mad here cant see there',
 'kwesidei whole crew',
 'need hug',
 'loltrish hey long time see yes rains bit only bit lol  im fine thanks  hows ',
 'tatianak nope',
 'twittera que muera ',
 'spring break plain city snowing',
 'repierced ears',
 'caregiving bear watch it thought ua loss embarrassing     ',
 'octolinz counts idk either never talk anymore',
 'smarrison wouldve first gun really though zac snyders doucheclown',
 'iamjazzyfizzle wish got watch you miss iamlilnicki premiere',
 'hollis death scene hurt severely watch film wry directors cut now',
 'file taxes',
 'lettya ahh ive always wanted see rent love soundtrack',
 'fakerpattypattz oh dear drinking forgotten table drinks',
 'alydesigns day get much done',
 'one friend called me asked meet mid valley todaybut iv

In [ ]:
print(sentences[0])
print(labels[0])

upset cant update facebook texting it might cry result school today also blah
0


In [ ]:
#Tokenize the sentences
tokenizer = Tokenizer()

#preparing vocabulary
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

size_of_vocabulary=len(word_index) + 1 
print("Vocabulary Size = %d"%size_of_vocabulary)

Vocabulary Size = 556418


In [ ]:
# split the data into a training set and a validation set
indices = np.arange(len(sentences))
print(indices)
#print(len(indices))
np.random.shuffle(indices)
print(indices)
#print(len(indices))

[      0       1       2 ... 1048572 1048573 1048574]
[ 183579  702300  280376 ...  774114 1031113  520203]


In [ ]:
sentences=np.array(sentences)[indices.astype(int)]
labels=np.array(labels)[indices.astype(int)]

In [ ]:
sentences[500]

'yaksierra a sorry hear little robin'

In [ ]:
labels[500]

0

In [ ]:
training_size = int(len(sentences) * 0.9)

training_sentences = sentences[0: training_size]
testing_sentences = sentences[training_size:]
training_labels = labels[0: training_size]
testing_labels = labels[training_size:]

# Put labels into list to use later:

training_labels_final = np.array(training_labels)
testing_labels_final = np.array(testing_labels)

In [ ]:
print("Shape of training dataset X : "+str(len(training_sentences)))
print("Shape of training dataset Y : "+str(len(training_labels_final)))
print("Shape of testing dataset X : "+str(len(testing_sentences)))
print("Shape of testing dataset Y : "+str(len(testing_labels_final)))

Shape of training dataset X : 943717
Shape of training dataset Y : 943717
Shape of testing dataset X : 104858
Shape of testing dataset Y : 104858


In [ ]:
embedding_dim = 100
max_length = 100
trunc_type='post'
padding_type='post'

In [ ]:
training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_padded = pad_sequences(training_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

In [ ]:
print(training_sentences[20])
print(training_sequences[20])
training_padded[20]


crs essay handed in
[21686, 1322, 4674, 441]


array([21686,  1322,  4674,   441,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0], dtype=int32)

In [ ]:
embeddings_index = dict()
f = open('/content/drive/MyDrive/glove.twitter.27B.100d.txt')

for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs

f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 1193514 word vectors.


In [ ]:
# create a weight matrix for words in training docs
embedding_matrix = np.zeros((size_of_vocabulary, 100))

for word, i in tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [ ]:
embedding_matrix.shape

(556418, 100)

In [ ]:
from keras.models import *
from keras.layers import *
from keras.callbacks import *

embedding_layer = Embedding(size_of_vocabulary, embedding_dim, weights = [embedding_matrix], input_length = max_length, trainable = False)
model = Sequential()
model.add(embedding_layer)

model.add(LSTM(200, dropout = 0.2))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation = "sigmoid"))

#Add loss function, metrics, optimizer
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=["acc"]) 

#Adding callbacks
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience=3)  
mc=ModelCheckpoint('best_model.h5', monitor='val_acc', mode='max', save_best_only=True,verbose=1)
reduce_lr = ReduceLROnPlateau(monitor = 'val_acc', factor = 0.1,min_lr = 0.01,verbose=1)

In [ ]:
#Print summary of model
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 100)          55641800  
                                                                 
 lstm (LSTM)                 (None, 200)               240800    
                                                                 
 dense (Dense)               (None, 64)                12864     
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 55,895,529
Trainable params: 253,729
Non-trainable params: 55,641,800
_________________________________________________________________
None


In [ ]:
history = model.fit(training_padded,training_labels_final,batch_size=1024,epochs=15,validation_data=(testing_padded,testing_labels_final),verbose=1,callbacks=[es,mc,reduce_lr])

Epoch 1/15
922/922 [==============================] - ETA: 0s - loss: 0.5506 - acc: 0.7630
Epoch 00001: val_acc improved from -inf to 0.76205, saving model to best_model.h5
922/922 [==============================] - 157s 163ms/step - loss: 0.5506 - acc: 0.7630 - val_loss: 0.5487 - val_acc: 0.7620 - lr: 0.0010
Epoch 2/15
922/922 [==============================] - ETA: 0s - loss: 0.5478 - acc: 0.7630
Epoch 00002: val_acc did not improve from 0.76205
922/922 [==============================] - 150s 163ms/step - loss: 0.5478 - acc: 0.7630 - val_loss: 0.5488 - val_acc: 0.7620 - lr: 0.0010
Epoch 3/15
193/922 [=====>........................] - ETA: 1:55 - loss: 0.5490 - acc: 0.7620

In [ ]:
with open('model_architecture_Twitter_classifier_second_try.json','w') as f:
    f.write(model.to_json())

In [ ]:
model.save_weights('Twitter_Classifier_second_try.h5')

In [ ]:
#Let us test some  samples
test_sample_1 = "I'm overwhelmed with happiness. Such an awesome experience at Lords"
test_sample_2 = "I am very sad"
test_sample_3 = "Hated it"

test_samples = [test_sample_1, test_sample_2,test_sample_3]

test_samples=[i.lower() for i in test_samples]
test_samples=[remove_stopwords(i) for i in test_samples]
test_samples=[remove_punctuations(i) for i in test_samples]
test_samples=[remove_URLs(i) for i in test_samples]
test_samples=[remove_numbers(i) for i in test_samples]

In [ ]:
test_samples

['im overwhelmed happiness awesome experience lords', 'sad', 'hated']

In [ ]:
test_samples_tokens = tokenizer.texts_to_sequences(test_samples)
test_samples_tokens_pad = pad_sequences(test_samples_tokens, maxlen=max_length)

#predict
model.predict(x=test_samples_tokens_pad)

array([[0.5882838 ],
       [0.2549563 ],
       [0.17931496]], dtype=float32)